name: Build WF
on:
  push:
    branches: 
      - main
  #pull request trigger
  pull_request:
    branches:
      - main
permissions: 
  contents: read 

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven Build
        run: mvn install

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Vprofile-App
          path: target/*.war 

      - name: Notify if Build Fails
        if: failure()
        run: echo "Build Failed"
    
  Testing: 
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Run tests on main branches
        run: mvn test 
      
      - name: Run Tests on Main Branch 
        if: github.ref == 'refs/heads/main'
        run: mvn install

      - name: Run Test rather than main Branch
        if: github.ref != 'refs/heads/main'
        run: mvn install

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

  Security_Scan:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run Trivy File System Scan 
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          format: 'json'
          scan-ref: .
          exit-code: 0
          vuln-type: 'os,library'
          output: trivy-results.json
        
      - name: Stroring Security Reports table
        uses: actions/upload-artifact@v4
        with:
          name: Trivy Results Storing
          path: target/*.json

